openapi: "3.0.1"
info:
  title: Api
  version: "1.0"
paths:
  /api/products/:
    get:
      summary: Gets all products
      tags: 
        - "Products"
      responses: 
        "200":
          description: Succesfully got all products
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/Product"
        "400":
          description: Bad request
        "500":
          description: Internal server error
    post:
      summary: Adds one product to the db
      tags: 
        - "Products"
      responses: 
        "200":
          description: Succesfully saved product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: Bad request
        "500":
          description: Internal server error
  /api/products/{pid}:
    get:
      summary: Get one user by id
      tags: 
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: product's id that's being search
          schema:
            type: string
      responses:
        "200":
          description: Succesfully got a product by Id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: Bad request
        "500":
          description: Internal server error
    put:
      summary: Updates an existing product
      tags: 
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: product's id
          schema:
           type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/updateProduct"
    delete:
      summary: Deletes an existing product
      tags: 
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: product's id
          schema:
           type: string
      responses:
        "200":
          description: Succesfully deleted a product by Id
        "400":
          description: Bad request
        "500":
          description: Internal server error

components:
  schemas:
    Product:
      type: object
      properties:
        _id: 
          type: string
          description: Id de mongodb
        title:
          type: string
          description: product's title
        description:
          type: string
          description: product's description
        code:
          type: string,
          description: business product's catalog number
        price:
          type: number
          description: indicates product's value
        status:
          type: boolean
          description: indicates if the product is available
        stock:
          type: number
          description: quantity of available product
        category:
          type: string
          description: tag category for the product
        thumbnails:
          type: array
          description: Array of images of the product
      example:
        _id: "63fea9bced198a34e995d081"
        title: "remera verde"
        description: "remera verde mujer"
        code: "abc150"
        price: "5000"
        status: true
        stock: "13"
        category: "remera"
        thumbnails: [
                    "https://i.pinimg.com/originals/65/f4/c3/65f4c3bb5588b943838a05ec58afb83b.webp"
                    ]
  requestBodies:
    updateProduct:
      properties:
        title:
          type: string
          description: product's title
        description:
          type: string
          description: product's description
        code:
          type: string,
          description: business product's catalog number
        price:
          type: number
          description: indicates product's value
        status:
          type: boolean
          description: indicates if the product is available
        stock:
          type: number
          description: quantity of available product
        category:
          type: string
          description: tag category for the product
        thumbnails:
          type: array
          description: Array of images of the product
      example:
        title: "remera verde"
        description: "remera verde mujer"
        code: "abc150"
        price: "5000"
        status: true
        stock: "13"
        category: "remera"
        thumbnails: [
                    "https://i.pinimg.com/originals/65/f4/c3/65f4c3bb5588b943838a05ec58afb83b.webp"
                    ]